{% set version = "0.2.2" %}

package:
  name: "bioformats2raw"
  version: "{{ version }}"

build:
  noarch: python
  number: 6

source:
  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version }}/bioformats2raw-{{ version }}.zip
  sha256: e7b8299933d4a4ae54ab1bc52d87531b67db34078cb184e94727a2f8604df792

requirements:
  host:
    - pip
    - python
  run:
    - blosc
    - openjdk >=8
    - python

test:
  commands:
    - bioformats2raw a.fake output
    - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
