on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install conda build
        run: conda install -y -q conda-build conda-verify
      - name: Conda build
        run: conda build .

  # TODO: upload to anaconda
  # Since this is a noarch package it is done from just one os
